# Generated by Django 6.0.1 on 2026-01-09 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_type', models.CharField(choices=[('one-way', 'One Way'), ('round-trip', 'Round Trip'), ('multi-city', 'Multi City')], max_length=20)),
                ('from_city', models.CharField(blank=True, max_length=100, null=True)),
                ('to_city', models.CharField(blank=True, max_length=100, null=True)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('passengers', models.PositiveIntegerField(default=1)),
                ('direct_only', models.BooleanField(default=False)),
                ('flexible_dates', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MultiCitySegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_city', models.CharField(max_length=100)),
                ('to_city', models.CharField(max_length=100)),
                ('travel_date', models.DateField()),
                ('flight_search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='ticket.flightsearch')),
            ],
        ),
    ]
